@startuml
package org.taranix.cafe.beans.scanner.ServiceClass {
["(Constructor) org.taranix.cafe.beans.scanner.ServiceClass()"] as org.taranix.cafe.beans.scanner.ServiceClass.org.taranix.cafe.beans.scanner.ServiceClass.Constructor
["(Field) magicNumber"] as org.taranix.cafe.beans.scanner.ServiceClass.magicNumber.Field
}

package org.taranix.cafe.beans.scanner.FactoryClass {
["(Constructor) org.taranix.cafe.beans.scanner.FactoryClass()"] as org.taranix.cafe.beans.scanner.FactoryClass.org.taranix.cafe.beans.scanner.FactoryClass.Constructor
["(Method) magicNumber()"] as org.taranix.cafe.beans.scanner.FactoryClass.magicNumber.Method
}


org.taranix.cafe.beans.scanner.FactoryClass.magicNumber.Method-->org.taranix.cafe.beans.scanner.FactoryClass.org.taranix.cafe.beans.scanner.FactoryClass.Constructor
org.taranix.cafe.beans.scanner.ServiceClass.magicNumber.Field-->org.taranix.cafe.beans.scanner.ServiceClass.org.taranix.cafe.beans.scanner.ServiceClass.Constructor
org.taranix.cafe.beans.scanner.ServiceClass.magicNumber.Field-->org.taranix.cafe.beans.scanner.FactoryClass.magicNumber.Method

@enduml

