@startuml
object Type
object ParametrizedType{
    Type : arguments
}
object Class {
    Class: constructor (Type[] arguments)
    Type : method (Type[] arguments)
    Type : field
}

Type <|-- ParametrizedType
Type <|-- Class

' Resolvers
object ConstructorResolver
object FieldResolver
object MethodResolver


object ClassResolver{
}

ClassResolver --> Class : resolving
ConstructorResolver --> Class : resolving constructor
FieldResolver --> Class : resolving constructor
MethodResolver --> Class : resolving constructor
@enduml